// MVP: Customers and Orders


Table customers {
  id integer [primary key]
  name varchar
  email varchar
  phone varchar
  address varchar
  created_at timestamp
}

Table orders {
  id integer [primary key]
  order_date date
  total_amount decimal
  customer_id integer [not null]
}


// STRETCH: Add Products and OrderProducts (join table)

Table products {
  id integer [primary key]
  name varchar
  price decimal
}

Table order_products {
  order_id integer [not null]
  product_id integer [not null]
  quantity integer
  created_at timestamp
}

Ref: orders.customer_id > customers.id // customers.id 1 < orders.customer_id *
Ref: order_products.order_id > orders.id // orders.id 1 < order_products.order_id *
Ref: order_products.product_id > products.id // products.id 1 < order_products.product_id *